apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  labels:
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express
        ports:
        - containerPort: 8081 # you can open mltiple ports on a container
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME # environment variable referenced from docker image docs
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD # environment variable referenced from docker image docs
          valueFrom: 
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
        - name: ME_CONFIG_MONGODB_SERVER # environment variable referenced from docker image docs
          valueFrom: 
            configMapKeyRef: # since database url is not a property which is supposed to be secret, it is referenced from configMap
              name: mongodb-configmap 
              key: database_url 
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service # external service for express webserver
spec:
  selector:
    app: mongo-express
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30000
